### ISSUE TITLE
Build with new version of RocRail

### ISSUE THREAD

**Issue by MobaOldie** [evili/rocrail-docker#2]
Hello, thanks for the Docker build. It was very helpful and enabled me to carry out the first tests for my model railway system using a CS3plus, a Synology DS916 and a MacBook with the RocRail software. The results so far have been very encouraging to continue. But there are new versions for RocRail available and I'm not very experienced with the Docker functionality to create new builds. Therefore the question is whether there will be another update to a newer RocRail version. Thank you for your feedback.

**Comment by evili** [comment]
Hi, 

Thanks for your attention. Solved by:

https://github.com/evili/rocrail-docker/commit/dca167721c2de9b8fb473da4cfe19c7e774ec752

Remember that you can "inject" the Rocrail version at build time with --build-arg=ROCRAIL_VERSION=xyzw

**Comment by MobaOldie** [comment]
Hi, super and thank you agin for the quick response and hints.
